name: Automatic Revert

on:
  workflow_dispatch:

jobs:
  revert-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Reverts to earlier commit
        run : |
            git revert cc1626a79079e444795df03be1f984c3457c9167
