name: PRs to master

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    #- name: Merge master back to dev
    # run: |
    #     git fetch --unshallow
    #      git checkout Dev_test
     #     git pull
      #    git merge --no-ff UAT_test -m "Auto-merge UAT_test back to dev_test"
       #   git push

