# This is a basic workflow to help you get started with Actions

name: Branch_Merge

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source Branch to merge'
        required: true
      target_branch:
        description: 'Target Branch to merge'
        required: true

jobs:

  Dev_to_UAT:
    runs-on: ubuntu-latest
    #needs: Feature_to_Dev
    environment: UAT
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.event.inputs.source_branch }}
          target_branch: ${{ github.event.inputs.target_branch }}
          #commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
