# This is a basic workflow to help you get started with Actions

name: Branch_Merge

on:
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: 'Dev_test'
          target_branch: 'UAT_test'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
 
  
