name: Push File

on:
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT_RB }}
      with:
        source_file: '.github'
        destination_repo: 'RahulBacche/Actionn'
        #destination_folder: 
        user_email: 'rahulbacche3@gmail.com'
        user_name: 'RahulBacche'
        commit_message: 'A custom message for the commit'
