name: Push File

on:
    workflow_dispatch:
      

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT_RB }}
      with:
        source_folder: '.github'
        destination_repo: 'RahulBacche/test3'
        #destination_folder: 
        user_email: 'rahulbacche3@gmail.com'
        user_name: 'RahulBacche'
        commit_msg: 'Uploading github actions'
