name: Rebase_2

on:
  workflow_dispatch:
    inputs:
      default_branch:
        description: 'Source Branch of Rebase'
        required: true
      target_branch:
        description: 'Target Branch to Rebase'
        required: true
   
jobs:
  test:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/checkout@v2
      - name: ReSync Branch_1
        uses: Joao208/resync-branch@1.5.0
        with:
          PERSONAL_TOKEN: ${{secrets.PAT_RB}}
          BRANCH_NAME: ${{ github.event.inputs.target_branch }}
          DEFAULT_BRANCH: ${{ github.event.inputs.default_branch }}
