name: Rebase_2

on:
  workflow_dispatch:
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ReSync Branch
        uses: Joao208/resync-branch@1.5.0
        with:
          PERSONAL_TOKEN: ${{secrets.PERSONAL_TOKEN}}
          BRANCH_NAME: Feature1
          DEFAULT_BRANCH: Dev_test
