name: Rebase_1
on:
  workflow_dispatch:    

jobs:
  rebase_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase head_branch on base_ref
        # Recommended: specify a version such as `@v1.0` rather than `@main`
        uses: DeeDeeG/rebase-github-action@main
        with:
          # Head branch, which will be rebased onto the base_ref.
          head_branch: Dev_test
          # Branch, or Git ref, that the head_branch will be rebased onto.
          base_ref: Feature1
