name : Revert by Gitbash 

on :
   workflow_dispatch:

jobs:
  revert-commit-2:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name: setup git config
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name : update git pull
        run: |
            git pull
            git log -2
            
      - name : Checkout UAT branch
        run: |
            git checkout Workflows           
            
      - name : Revert Head
        run: |            
            git revert HEAD
            git push
