name : Revert

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to revert'
        required: true
        type: string
        
      commit_id:
        description: 'Commit ID'
        required: true
        type: string
        
    secrets:
      token:
        required: true

jobs:
  reverting-last-commit:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name : Checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.token}}
          fetch-depth: 0

      - name: setup git config
        run: |
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "{{ github.actor }}@users.noreply.github.com"
      
      - name : update git pull
        run: |
            git pull
            git log -2
            
      - name : Checkout branch
        run: |
            git checkout ${{ github.event.inputs.branch }}           
            
      - name : Revert Head
        run: |            
            git revert  ${{ github.event.inputs.commit_id }} -m1
            git push
