name: Sync_Databricks_Dev

on:
  workflow_call:
    secrets:
      DEV_REPO_ID:
        required: true
      DEV_PAT:
        required: true
        


jobs:
  Synchronizing:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -s -n -X PATCH  "https://nbcu-cds-dev.cloud.databricks.com/api/2.0/repos/${{ secrets.DEV_REPO_ID }}" -H "Authorization: Bearer ${{ secrets.DEV_PAT }}" -d '{"branch": "dev"}'
